package dk.silverbullet.kihdb.service.dkgs.monitoringdataset.version1_0_2

import dk.silverbullet.kihdb.service.dgks.generated.monitoringdataset.version1_0_2.*

import javax.jws.WebMethod
import javax.jws.WebParam
import javax.jws.WebResult
import javax.jws.WebService

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-07-16T06:19:26.293+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:oio:medcom:monitoringdataset:1.0.1", name = "MonitoringDatasetPortType")
//@XmlSeeAlso({ObjectFactory.class})
//@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface V102MonitoringDatasetPortType {

    @WebResult(name = "DeleteMonitoringDatasetResponseMessage", targetNamespace = "urn:oio:medcom:monitoringdataset:1.0.1", partName = "parameter")
    @WebMethod(operationName = "DeleteMonitoringDataset", action = "DeleteMonitoringDataset")
    public DeleteMonitoringDatasetResponseMessage deleteMonitoringDataset(
        @WebParam(partName = "parameter", name = "DeleteMonitoringDatasetRequestMessage", targetNamespace = "urn:oio:medcom:monitoringdataset:1.0.1")
        DeleteMonitoringDatasetRequestMessage parameter
    ) throws FaultMessage;

    @WebResult(name = "CreateMonitoringDatasetResponseMessage", targetNamespace = "urn:oio:medcom:monitoringdataset:1.0.1", partName = "parameter")
    @WebMethod(operationName = "CreateMonitoringDataset", action = "CreateMonitoringDataset")
    public CreateMonitoringDatasetResponseMessage createMonitoringDataset(
        @WebParam(partName = "parameter", name = "CreateMonitoringDatasetRequestMessage", targetNamespace = "urn:oio:medcom:monitoringdataset:1.0.1")
        CreateMonitoringDatasetRequestMessage parameter
    ) throws FaultMessage;

    @WebResult(name = "GetMonitoringDatasetResponseMessage", targetNamespace = "urn:oio:medcom:monitoringdataset:1.0.1", partName = "parameter")
    @WebMethod(operationName = "GetMonitoringDataset", action = "GetMonitoringDataset")
    public GetMonitoringDatasetResponseMessage getMonitoringDataset(
        @WebParam(partName = "parameter", name = "GetMonitoringDatasetRequestMessage", targetNamespace = "urn:oio:medcom:monitoringdataset:1.0.1")
        GetMonitoringDatasetRequestMessage parameter
    ) throws FaultMessage;
}
