/**
 * Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.silverbullet.kihdb.client.dgks.monitoring.version1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-21T08:31:37.278+01:00
 * Generated source version: 2.6.2
 */
@WebService(targetNamespace = "urn:oio:medcom:chronicdataset:monitoring:1.0.0", name = "MonitoringPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MonitoringPortType {

    @WebResult(name = "CreateMonitoringResponseMessage", targetNamespace = "urn:oio:medcom:chronicdataset:monitoring:1.0.0", partName = "parameter")
    @WebMethod(operationName = "CreateMonitoring", action = "CreateMonitoring")
    public CreateMonitoringResponseMessage createMonitoring(
            @WebParam(partName = "parameter", name = "CreateMonitoringRequestMessage", targetNamespace = "urn:oio:medcom:chronicdataset:monitoring:1.0.0")
            CreateMonitoringRequestMessage parameter
    ) throws FaultMessage;

    @WebResult(name = "DeleteMonitoringResponseMessage", targetNamespace = "urn:oio:medcom:chronicdataset:monitoring:1.0.0", partName = "parameter")
    @WebMethod(operationName = "DeleteMonitoring", action = "DeleteMonitoring")
    public DeleteMonitoringResponseMessage deleteMonitoring(
            @WebParam(partName = "parameter", name = "DeleteMonitoringRequestMessage", targetNamespace = "urn:oio:medcom:chronicdataset:monitoring:1.0.0")
            DeleteMonitoringRequestMessage parameter
    ) throws FaultMessage;
}
