/**
 * Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dk.silverbullet.kihdb.client.dgks.monitoring.version1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-21T08:31:37.222+01:00
 * Generated source version: 2.6.2
 */
public final class MonitoringPortType_MonitoringPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:oio:medcom:chronicdataset:monitoring:1.0.0", "MonitoringService");

    private MonitoringPortType_MonitoringPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MonitoringService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MonitoringService ss = new MonitoringService(wsdlURL, SERVICE_NAME);
        MonitoringPortType port = ss.getMonitoringPort();

        {
            System.out.println("Invoking createMonitoring...");
            dk.silverbullet.kihdb.client.dgks.monitoring.version1.CreateMonitoringRequestMessage _createMonitoring_parameter = null;
            try {
                dk.silverbullet.kihdb.client.dgks.monitoring.version1.CreateMonitoringResponseMessage _createMonitoring__return = port.createMonitoring(_createMonitoring_parameter);
                System.out.println("createMonitoring.result=" + _createMonitoring__return);

            } catch (FaultMessage e) {
                System.out.println("Expected exception: FaultMessage has occurred.");
                System.out.println(e.toString());
            }
        }
        {
            System.out.println("Invoking deleteMonitoring...");
            dk.silverbullet.kihdb.client.dgks.monitoring.version1.DeleteMonitoringRequestMessage _deleteMonitoring_parameter = null;
            try {
                dk.silverbullet.kihdb.client.dgks.monitoring.version1.DeleteMonitoringResponseMessage _deleteMonitoring__return = port.deleteMonitoring(_deleteMonitoring_parameter);
                System.out.println("deleteMonitoring.result=" + _deleteMonitoring__return);

            } catch (FaultMessage e) {
                System.out.println("Expected exception: FaultMessage has occurred.");
                System.out.println(e.toString());
            }
        }

        System.exit(0);
    }

}
