/**
 * Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dk.silverbullet.kihdb.client.dgks.chronicdataset.version1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-25T12:28:08.501+01:00
 * Generated source version: 2.6.2
 */
public final class ChronicDatasetPortType_ChronicDatasetPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:oio:medcom:chronicdataset:all:1.0.0", "ChronicDatasetService");

    private ChronicDatasetPortType_ChronicDatasetPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ChronicDatasetService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ChronicDatasetService ss = new ChronicDatasetService(wsdlURL, SERVICE_NAME);
        ChronicDatasetPortType port = ss.getChronicDatasetPort();

        {
            System.out.println("Invoking getChronicDataset...");
            dk.silverbullet.kihdb.client.dgks.chronicdataset.version1.GetChronicDatasetRequestMessage _getChronicDataset_parameter = null;
            try {
                dk.silverbullet.kihdb.client.dgks.chronicdataset.version1.GetChronicDatasetResponseMessage _getChronicDataset__return = port.getChronicDataset(_getChronicDataset_parameter);
                System.out.println("getChronicDataset.result=" + _getChronicDataset__return);

            } catch (FaultMessage e) {
                System.out.println("Expected exception: FaultMessage has occurred.");
                System.out.println(e.toString());
            }
        }

        System.exit(0);
    }

}
