/**
 * Copyright 2014 Stiftelsen for Software-baserede Sundhedsservices - 4S
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.silverbullet.kihdb.client.dgks.chronicdataset.version1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-25T12:28:08.572+01:00
 * Generated source version: 2.6.2
 */
@WebService(targetNamespace = "urn:oio:medcom:chronicdataset:all:1.0.0", name = "ChronicDatasetPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ChronicDatasetPortType {

    @WebResult(name = "GetChronicDatasetResponseMessage", targetNamespace = "urn:oio:medcom:chronicdataset:all:1.0.0", partName = "parameter")
    @WebMethod(operationName = "GetChronicDataset", action = "GetChronicDataset")
    public GetChronicDatasetResponseMessage getChronicDataset(
            @WebParam(partName = "parameter", name = "GetChronicDatasetRequestMessage", targetNamespace = "urn:oio:medcom:chronicdataset:all:1.0.0")
            GetChronicDatasetRequestMessage parameter
    ) throws FaultMessage;
}
